### PR TITLE
Initial Windows agent support

### PR DESCRIPTION
**Pull request by slide**
This will require the PR for https://github.com/jenkinsci/docker-slave to be merged and pushed to docker hub.

### CODE REVIEW

**Comment by mluyo3414** [comment]
Tested in AKS k8s preview 1.14

**Comment by slide** [comment]
Any feedback on the doc updates? If those look ok, I'm planning on merging this.

**Comment by markyjackson-taulia** [comment]
@slide  this looks awesome

**Comment by mluyo3414** [comment]
I created this as a follow up when trying to have two JNLP containers (I never had to different JNLP containers so wondering if this works out): https://issues.jenkins-ci.org/browse/JENKINS-57256 . Not related to the image PR directly.

**Comment by mluyo3414** [comment]
^^^ I had a bug in my container definition. Image worked well - https://github.com/mluyo3414org/pod-templates

**Pull request merged**
