### PR TITLE
download slave.jar from master

### PR DESCRIPTION
**Pull request by win-t**
it's good if slave always use slave.jar that provide by master, so we don't need to worry about version compatibility

### CODE REVIEW

**Comment by carlossg** [comment]
The slave jar is included in the image already, this would just re-download it

**Comment by win-t** [comment]
yes, i know, that just to make sure that the client connect with correct version of slave.jar.

**Comment by win-t** [comment]
I don't know if the protocol support backward compatibility, AFAIK, the command that sent by Jenkins master to slave is serialized java object.
Actually, that happened in my production setup. My master was using an old remote.jar, the slave cannot to unserialized the java object, that is why I prefer to use the same version as served by the master.
About security issue, I think updating the master is the solution (that is what I do).

**Comment by oleg-nenashev** [comment]
>  My master was using an old remote.jar, the slave cannot to unserialized the java object, 

It's rather a bug then. I need more details about it, because it is not supposed to happen.

> that is why I prefer to use the same version as served by the master.

It is a preferable case for many cases, but not for all of them. Frequently people need to install custom remoting agents on agents in order to apply hotfixes without restarting the master.

> About security issue, I think updating the master is the solution (that is what I do).

Upgrade may cost man-months for large instances. Hotfixes are required sometimes.

Summary: I am still against making this behavior a default one. If there is no enforced remoting downgrade, it should be OK to merge.

**Comment by oleg-nenashev** [comment]
As it was discussed in the Windows service agent auto-upgrade PR (https://github.com/jenkinsci/windows-slave-installer-module/pull/6), we would like to avoid downloading of agents from non-HTTPs protocols. So it will also need to be checked here.

@win-t Any plans to work on this PR?

**Comment by win-t** [comment]
nah, at the end, many my client container is not derived from this image, 
I don't think I will work on this PR. Maybe someone else wants to continue it.

**Comment by carlossg** [comment]
FWIW downloading the jar is useful, but mainly in case you are *not* using this image but any other (with java installed)

**Pull request closed without merging**
