### PR TITLE
[WIP] Add initial Dockerfile for Windows

### PR DESCRIPTION
**Pull request by slide**
Depends on https://github.com/jenkinsci/docker-slave/pull/66

This adds a JNLP agent Dockerfile for Windows agents

### CODE REVIEW

**Comment by slide** [comment]
I marked this as WIP because there is currently no support on ci.j.io or trusted.ci for building Windows docker images.

**Comment by oleg-nenashev** [comment]
What about Dockerhub? Might be enough for now

**Comment by slide** [comment]
I'm not sure how all that works, still a bit new to docker :-)

**Comment by slide** [comment]
Will squash and create new PR

**Pull request closed without merging**
