### PR TITLE
[JENKINS-61409] - Upgrade to Remoting version 4.3 for WebSocket large payload fix

### PR DESCRIPTION
**Pull request by jeffret-b**
See [JENKINS-61409](https://issues.jenkins-ci.org/browse/JENKINS-61409).

Also see the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.3).

Dependent on jenkinsci/docker-slave#110.

### CODE REVIEW

**Comment by slide** [comment]
We need to wait for the docker-slave PR to land and a release of that container, correct?

**Comment by jeffret-b** [comment]
I think so. We need to improve that process. It's difficult to keep it all going and make sure it all proceeds through.

**Comment by mbarbero** [comment]
docker-slave [PR](https://github.com/jenkinsci/docker-slave/pull/110) has been merged, could this one be merged as well?

**Comment by oleg-nenashev** [comment]
A release for upstream is still needed. On it

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/docker-slave/releases/tag/4.3-1 is out

**Comment by jglick** [comment]
Note to self: will also need a `kubernetes` plugin update, especially once the backport to LTS occurs.

**Comment by jglick** [comment]
> a `kubernetes` plugin update

to amend https://github.com/jenkinsci/kubernetes-plugin/pull/748

**Comment by slide** [comment]
CI check done, merging.

**Comment by jglick** [comment]
So should appear soon under: https://hub.docker.com/r/jenkinsci/jnlp-slave/tags

**Pull request merged**
